spring:
  jpa:
    show-sql: true
    database: h2
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

server:
  port: 8081
